"""init_db

Revision ID: 6be626d9e75c
Revises: 
Create Date: 2026-04-22 05:56:38.180197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be626d9e75c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=True)
    op.create_table('centros_treinamento',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=60), nullable=False),
    sa.Column('proprietario', sa.String(length=30), nullable=False),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_centros_treinamento_id'), 'centros_treinamento', ['id'], unique=True)
    op.create_table('atletas',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('altura', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexo'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('centro_treinamento_id', sa.Integer(), nullable=False),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.pk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['centro_treinamento_id'], ['centros_treinamento.pk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_atletas_categoria_id'), 'atletas', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_atletas_centro_treinamento_id'), 'atletas', ['centro_treinamento_id'], unique=False)
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_centro_treinamento_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_categoria_id'), table_name='atletas')
    op.drop_table('atletas')
    op.drop_index(op.f('ix_centros_treinamento_id'), table_name='centros_treinamento')
    op.drop_table('centros_treinamento')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
